### ISSUE TITLE
Not sharing

### ISSUE THREAD

**Issue by simahawk** [acsone/git-autoshare#2]
I'm trying this but the shared clone never happen:
```bash

# cat ~/.config/git-autoshare/config.yml 
github.com:
    odoo-dj:
        - camptocamp

# git autoshare-clone https://github.com/camptocamp/odoo-dj
Cloning into 'odoo-dj'...
remote: Counting objects: 1487, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 1487 (delta 1), reused 7 (delta 1), pack-reused 1477
Receiving objects: 100% (1487/1487), 454.79 KiB | 181.00 KiB/s, done.
Resolving deltas: 100% (933/933), done.
Checking connectivity... done.

# ls odoo-dj/
[...]


# ls ~/.cache/git-autoshare
ls: cannot access '/home/sorsi/.cache/git-autoshare': No such file or directory
```

Any other place where this could be landed? Any way to verify what's going on (beside putting a pdb into autoshare ;)

**Comment by sbidoul** [comment]
Can you try renaming config.yml to repos.yml?

**Comment by simahawk** [comment]
jeez, I'm an idiot... that's why you should copy/paste straight from README :sob:
I'll add a check on that file for idiots like me :stuck_out_tongue_winking_eye:

**Comment by simahawk** [comment]
There you go https://github.com/acsone/git-autoshare/pull/3
